### ISSUE TITLE
[SECURITY]: Implement database encryption at rest for GDPR compliance

### ISSUE THREAD

**Issue by yungweng** [moto-nrw/project-phoenix#126]
## Problem Statement

Currently, the PostgreSQL database does not have encryption at rest enabled, which is a security gap for GDPR/DSGVO compliance when handling student personal data including minors' information.

## Current Status

- Database runs without encryption at rest
- SSL/TLS is disabled in both development and production (`sslmode=disable`)
- Student personal data is stored in plaintext on disk
- No protection against physical access to database files

## GDPR/DSGVO Requirements

Article 32 requires "appropriate technical and organizational measures" including encryption of personal data. For educational institutions handling minors' data, encryption at rest is considered a necessary safeguard.

### Option 1: PostgreSQL Transparent Data Encryption (TDE)
```yaml
# In docker-compose.prod.yml
postgres:
  environment:
    - POSTGRES_INITDB_ARGS=--data-checksums --wal-level=replica
    - POSTGRES_ENCRYPTION_KEY_FILE=/etc/postgres/encryption.key
  volumes:
    - encrypted_data:/var/lib/postgresql/data
    - ./config/postgres/encryption.key:/etc/postgres/encryption.key:ro
```

### Option 2: Filesystem-level encryption (LUKS)
```bash
# Encrypt the Docker volume mount point
cryptsetup luksFormat /dev/disk/for/postgres
cryptsetup open /dev/disk/for/postgres postgres_encrypted
```

### Option 3: Cloud provider encryption
- AWS RDS: `storage_encrypted = true`
- Azure Database: `storage_encrypted = true`
- GCP Cloud SQL: Automatic encryption

## Implementation Requirements

1. **Enable encryption at rest** for the PostgreSQL database
2. **Secure key management** for encryption keys
3. **Documentation** of encryption setup and key rotation procedures
4. **Environment configuration** for development, staging, and production
5. **Backup encryption** to ensure encrypted backups

## Security Considerations

- Encryption keys must be stored separately from encrypted data
- Key rotation procedures must be documented
- Backup and recovery procedures must maintain encryption
- Performance impact should be measured and documented

## Testing Plan

1. Test database performance with encryption enabled
2. Verify backup and restore procedures work with encryption
3. Test key rotation procedures
4. Validate that data is actually encrypted on disk

## Documentation Updates Needed

- Update deployment documentation with encryption setup
- Document key management procedures
- Update backup/restore procedures
- Add encryption status to monitoring/health checks

## Related Issues

- Issue #99: Audit and standardize all .env files to prevent security issues
- Issue #84: Configure admin password via environment variables

## Acceptance Criteria

- [ ] Database encryption at rest is enabled in production
- [ ] Encryption keys are securely managed and rotated
- [ ] Documentation is updated with encryption procedures
- [ ] Backup and restore procedures work with encryption
- [ ] Performance impact is measured and acceptable
- [ ] Encryption status is included in health checks
