### ISSUE TITLE
[SECURITY]: Enable SSL/TLS in production for GDPR compliance

### ISSUE THREAD

**Issue by yungweng** [moto-nrw/project-phoenix#127]
## Problem Statement

SSL/TLS is currently disabled in production (`sslmode=disable`) which violates GDPR/DSGVO requirements for data protection in transit. The infrastructure for SSL exists in the codebase but is not implemented.

## Current Status

- SSL/TLS disabled in both development and production environments
- `sslmode=disable` in all database connection strings
- SSL certificate infrastructure exists in `config/ssl/postgres/certs/` but is empty
- Documentation exists in `docs/ssl-setup.md` but not implemented

## GDPR/DSGVO Requirements

Article 32(1)(a) requires "the pseudonymisation and encryption of personal data" and "appropriate technical measures" including encryption in transit to protect against unauthorized access.

## Existing Infrastructure

The project already has SSL setup documentation and directory structure:
- `docs/ssl-setup.md` - SSL configuration guide
- `config/ssl/postgres/certs/` - Certificate directory (currently empty)
- Docker Compose configurations ready for SSL implementation

### 1. Database SSL/TLS
```yaml
# Update docker-compose.prod.yml
postgres:
  environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./config/ssl/postgres:/var/lib/postgresql/ssl:ro
  command: >
    postgres
    -c ssl=on
    -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
    -c ssl_key_file=/var/lib/postgresql/ssl/server.key
    -c ssl_ca_file=/var/lib/postgresql/ssl/ca.crt
```

### 2. Update Connection Strings
```bash
# Change from:
DB_DSN=postgres://user:pass@localhost:5432/db?sslmode=disable

# To:
DB_DSN=postgres://user:pass@localhost:5432/db?sslmode=require
```

### 3. Frontend/Backend HTTPS
```yaml
# Caddy configuration for HTTPS
caddy:
  volumes:
    - ./deployment/production/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
```

### Development Environment
- Use self-signed certificates for local development
- Document certificate generation process
- Include certificates in .gitignore

### Production Environment
- Use Let's Encrypt or proper CA-signed certificates
- Implement automatic certificate renewal
- Document certificate deployment process

## Implementation Steps

1. **Generate SSL Certificates**
   - Development: Self-signed certificates
   - Production: Let's Encrypt or CA-signed certificates

2. **Update Docker Configurations**
   - Enable SSL in PostgreSQL container
   - Configure Caddy for HTTPS termination
   - Update environment variables

3. **Update Connection Strings**
   - Change `sslmode=disable` to `sslmode=require`
   - Update all environment files and documentation

4. **Test SSL Implementation**
   - Verify database connections work with SSL
   - Test frontend/backend communication over HTTPS
   - Validate certificate chain and security headers

5. **Update Documentation**
   - Complete `docs/ssl-setup.md` with implementation details
   - Document certificate renewal procedures
   - Update deployment guides

## Security Considerations

- Certificate private keys must be protected (600 permissions)
- Implement proper certificate rotation
- Use strong TLS versions (TLS 1.2+)
- Configure secure cipher suites
- Implement HSTS headers for web traffic

## Testing Plan

1. Test database connections with SSL enabled
2. Verify all API endpoints work over HTTPS
3. Test certificate validation and chain verification
4. Performance testing with SSL overhead
5. Test certificate renewal procedures

## Documentation Updates

- Complete `docs/ssl-setup.md` with production setup
- Update deployment documentation
- Document certificate management procedures
- Update .env.example files with SSL connection strings

## Related Issues

- Issue #126: Implement database encryption at rest for GDPR compliance
- Issue #99: Audit and standardize all .env files to prevent security issues
- Issue #73: Implement proper long-term production setup

## Acceptance Criteria

- [ ] SSL/TLS enabled for PostgreSQL in production
- [ ] HTTPS enabled for frontend/backend communication
- [ ] All connection strings use `sslmode=require`
- [ ] Certificate management procedures documented
- [ ] SSL implementation tested and verified
- [ ] Performance impact measured and acceptable
- [ ] Security headers properly configured
